In [1]:
import pandas as pd
import numpy as np

In [2]:
# load the data 
df = pd.read_csv("student_data.csv")

print("Shape of the data :")
df.shape

Shape of the data :

(500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     500 non-null    int64
 1   Age            500 non-null    int64
 2   Math_Score     500 non-null    int64
 3   Science_Score  500 non-null    int64
 4   English_Score  500 non-null    int64
 5   Hours_Studied  500 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 23.6 KB

In [4]:
df.head()

   Student_ID  Age  Math_Score  Science_Score  English_Score  Hours_Studied
0           1   16          62             49             44            7.5
1           2   17          52             40             63            2.3
2           3   15          39             67             90            2.9
3           4   17          98             35             64            8.4
4           5   17          63             52             93            3.9

In [ ]:
# convert each columns in numpy 
age = df["Age"].values
math_score = df["Math_Score"].values
science_score = df["Science_Score"].values
english_score = df["English_Score"].values
hour_studied = df["Hours_Studied"].values

print("="*60)
print("Data Loaded !")
print(f"Type : {type(age)}")
print(f"Shape : {age.shape} - means 500 values in one row.")
print(f"dtype : {age.dtype} int64 means whole numbers")
print()
print("First 10 age scores:", age[:10])

print("="*60)
print("Data Loaded !")
print(f"Type : {type(math_score)}")
print(f"Shape : {math_score.shape} - means 500 values in one row.")
print(f"dtype : {math_score.dtype} int64 means whole numbers")
print()
print("First 10 math_score scores:", math_score[:10])
print("="*60)

print("="*60)
print("Data Loaded !")
print(f"Type : {type(science_score)}")
print(f"Shape : {science_score.shape} - means 500 values in one row.")
print(f"dtype : {science_score.dtype} int64 means whole numbers")
print()
print("First 10 science_score scores:", science_score[:10])

print("="*60)
print("Data Loaded !")
print(f"Type : {type(english_score)}")
print(f"Shape : {english_score.shape} - means 500 values in one row.")
print(f"dtype : {english_score.dtype} int64 means whole numbers")
print()
print("First 10 english_score scores:", english_score[:10])

print("="*60)
print("Data Loaded !")
print(f"Type : {type(hour_studied)}")
print(f"Shape : {hour_studied.shape} - means 500 values in one row.")
print(f"dtype : {hour_studied.dtype} int64 means whole numbers")
print()
print("First 10 hour_studied scores:", hour_studied[:10])

============================================================
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 age scores: [16 17 15 17 17 14 15 15 15 17]
============================================================
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 math_score scores: [62 52 39 98 63 81 39 48 87 30]
============================================================
============================================================
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 science_score scores: [49 40 67 35 52 76 75 41 42 91]
============================================================
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 english_score scores: [44 63 90 64 93 54 53 41 47 44]
============================================================
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : float64 int64 means whole numbers

First 10 hour_studied scores: [7.5 2.3 2.9 8.4 3.9 1.2 2.4 3.  9.6 6.2]

In [24]:
# add 5 bonus marks in each column 
math_bonous = math_score + 5 
print("Math_Score before adding bonus :" ,math_score[:5])
print("Math_Score after  adding bonus :" ,math_bonous[:5])

# check the percentage 
math_percentage = math_score/100 *100 
print("Math_score as percentage:", math_percentage[:5])

print()

# total score math+science + english 
total_score = math_score + science_score + english_score
print("Total score :", total_score[:5])
print("Max possible total score : 300")

Math_Score before adding bonus : [62 52 39 98 63]
Math_Score after  adding bonus : [ 67  57  44 103  68]
Math_score as percentage: [62. 52. 39. 98. 63.]

Total score : [155 155 196 197 208]
Max possible total score : 300

In [8]:
print("MATH SCORE STATISTICS")
# print("-"*35)
print(f" Mean (Average) : {np.mean(math_score):.2f}")
print(f" Median : {np.median(math_score):.2f}")
print(f" Std Deviation : {np.std(math_score):.2f}")
print(f" Minimum Score : {np.min(math_score):.2f}")
print(f" Maximum Score : {np.max(math_score):.2f}")
print(f" Total Sum      : {np.sum(math_score):.2f}")
print("="*60)
                                  
print("ENGLISH SCORE STATISTICS")
# print("-"*35)
print(f" Mean (Average) : {np.mean(english_score):.2f}")
print(f" Median : {np.median(english_score):.2f}")
print(f" Std Deviation : {np.std(english_score):.2f}")
print(f" Minimum Score : {np.min(english_score):.2f}")
print(f" Maximum Score : {np.max(english_score):.2f}")
print(f" Total Sum      : {np.sum(english_score)}")
print("="*60)

print("SCIENCE SCORE STATISTICS")
# print("-"*35)
print(f" Mean (Average) : {np.mean(science_score):.2f}")
print(f" Median : {np.median(science_score):.2f}")
print(f" Std Deviation : {np.std(science_score):.2f}")
print(f" Minimum Score : {np.min(science_score):.2f}")
print(f" Maximum Score : {np.max(science_score):.2f}")
print(f" Total Sum      : {np.sum(science_score)}")
print("="*60)

MATH SCORE STATISTICS
 Mean (Average) : 63.60
 Median : 63.00
 Std Deviation : 20.54
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 31802.00
============================================================
ENGLISH SCORE STATISTICS
 Mean (Average) : 63.84
 Median : 64.00
 Std Deviation : 20.17
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 31920
============================================================
SCIENCE SCORE STATISTICS
 Mean (Average) : 64.86
 Median : 65.50
 Std Deviation : 20.18
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 32428
============================================================

In [9]:
# 2. Extract the columns into the corresponding variables
math = df['Math_Score'].values
english = df['English_Score'].values
science = df['Science_Score'].values
hours = df['Hours_Studied'].values

# --- 3. Now run your original analysis code ---

# Students who scored above 80 in English
high_scorers = english[english > 80]
print(f' Students scoring above 80 in English: {len(high_scorers)} students')
print('Their scores (first 10):', high_scorers[:10])

print()

# Students who studied more than 7 hours
hardworking = hours[hours > 7]
print(f' Students studying more than 7 hrs/day: {len(hardworking)}')

print()

# Students who scored > 80 in BOTH English AND Science
top_in_both = (english > 80) & (science > 80)
print(f' Students scoring > 80 in both English & Science: {np.sum(top_in_both)}')

 Students scoring above 80 in English: 117 students
Their scores (first 10): [ 90  93  89  82 100  93  82  89 100  89]

 Students studying more than 7 hrs/day: 163

 Students scoring > 80 in both English & Science: 31

In [ ]:
high_scorers = math[math > 80]
print(f' Students scoring above 80 in Math: {len(high_scorers)} students')
print('Their scores (first 10):', high_scorers[:10])

print()

hardworking = hours[hours > 7]
print(f' Students studying more than 7 hrs/day: {len(hardworking)}')

print()

top_in_both = (english > 80) & (math > 80)
print(f' Students scoring > 80 in both English & Math: {np.sum(top_in_both)}')

 Students scoring above 80 in Math: 117 students
Their scores (first 10): [ 90  93  89  82 100  93  82  89 100  89]

 Students studying more than 7 hrs/day: 163

 Students scoring > 80 in both English & Math: 25

In [11]:
high_scorers = science[science > 80]
print(f' Students scoring above 80 in Science: {len(high_scorers)} students')
print('Their scores (first 10):', high_scorers[:10])

print()

hardworking = hours[hours > 8]
print(f' Students studying more than 8 hrs/day: {len(hardworking)}')

print()

# --- Students who scored > 80 in Science AND studied more than 8 hours ---
top_science_and_hours = (science > 80) & (hours > 8)
print(f' Students scoring > 80 in Science & studying more than 8 hours: {np.sum(top_science_and_hours)}')

 Students scoring above 80 in Science: 139 students
Their scores (first 10): [91 89 97 83 86 92 83 84 82 81]

 Students studying more than 8 hrs/day: 103

 Students scoring > 80 in Science & studying more than 8 hours: 29

In [ ]:
scores_2d = np.column_stack([math ,english, science])

print('Shape of 2D array:', scores_2d.shape)  # Should be (500, 3)
print('  → 500 rows (students), 3 columns (subjects)\n')

print('First 5 rows (students):')
print('  Math | English | Science')
print(scores_2d[:5])

print()

subject_avg = np.mean(scores_2d, axis=0)
print(f' Average by Subject:')
print(f'  Math    : {subject_avg[0]:.2f}')
print(f'  Science : {subject_avg[1]:.2f}')
print(f'  English : {subject_avg[2]:.2f}')\

print()

std_avg = np.mean(scores_2d, axis=1)
print('Average score per student (first 5):', np.round(std_avg[:5], 2))

Shape of 2D array: (500, 3)
  → 500 rows (students), 3 columns (subjects)

First 5 rows (students):
  Math | Science | English
[[62 44 49]
 [52 63 40]
 [39 90 67]
 [98 64 35]
 [63 93 52]]

 Average by Subject:
  Math    : 63.60
  Science : 63.84
  English : 64.86

Average score per student (first 5): [51.67 51.67 65.33 65.67 69.33]

In [16]:
array = np.arange(1, 61)
print('Original 1D array:', array)
print('Shape:', array.shape)

print()

# Reshape into 10 rows x 6 columns
array_2d = array.reshape(10, 6)
print('Reshaped to 10x6:')
print(array_2d)

print()

# Reshape into 6 rows x 10 columns
array_2d_b = array.reshape(6, 10)
print('Reshaped to 6x10:')
print(array_2d_b)

print()

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
Shape: (60,)

Reshaped to 10x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]

Reshaped to 6x10:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]

In [17]:
# np.unique() -> find all unique values (no repeats)
unique_ages = np.unique(age)
print('Unique ages in our data:', unique_ages)

print()

# np.percentile() -> like "top X%"
p25 = np.percentile(math, 25)  # 25th percentile
p50 = np.percentile(math, 50)  # 50th percentile
p75 = np.percentile(math, 75)  # 75th percentile
print(f'Math Score Percentiles:')
print(f'  25th percentile: {p25} - Bottom 25% scored below this')
print(f'  50th percentile: {p50} - Middle score (50% scored below/above this)')
print(f'  75th percentile: {p75} - Top 25% scored above this')

print()

# np.clip() -> limit values between a min and max
# Let's say max score allowed is 95
math_capped = np.clip(math, 0, 95)
print(f'Original max math score : {np.max(math)}')
print(f'After capping at 95     : {np.max(math_capped)}')

print()

# np.where() -> like IF-ELSE for arrays!
# Give grade 'Pass' if score >= 50, else 'Fail'
result = np.where(math >= 50, 'Pass', 'Fail')
pass_count = np.sum(result == 'Pass')
fail_count = np.sum(result == 'Fail')
print(f'Math Pass/Fail:')
print(f'  Pass: {pass_count} students')
print(f'  Fail: {fail_count} students')

Unique ages in our data: [13 14 15 16 17 18]

Math Score Percentiles:
  25th percentile: 46.0 - Bottom 25% scored below this
  50th percentile: 63.0 - Middle score (50% scored below/above this)
  75th percentile: 81.0 - Top 25% scored above this

Original max math score : 100
After capping at 95     : 95

Math Pass/Fail:
  Pass: 348 students
  Fail: 152 students

In [18]:
# np.unique() -> find all unique values (no repeats)
unique_ages = np.unique(age)
print('Unique ages in our data:', unique_ages)

print()

# np.percentile() -> like "top X%"
p25 = np.percentile(english, 25)  # 25th percentile
p50 = np.percentile(english, 50)  # 50th percentile
p75 = np.percentile(english, 75)  # 75th percentile
print(f'English Score Percentiles:')
print(f'  25th percentile: {p25} - Bottom 25% scored below this')
print(f'  50th percentile: {p50} - Middle score (50% scored below/above this)')
print(f'  75th percentile: {p75} - Top 25% scored above this')

print()

# np.clip() -> limit values between a min and max
# Let's say max score allowed is 95
english_capped = np.clip(english, 0, 95)
print(f'Original max English score : {np.max(english)}')
print(f'After capping at 95     : {np.max(english_capped)}')

print()

# np.where() -> like IF-ELSE for arrays!
# Give grade 'Pass' if score >= 50, else 'Fail'
result = np.where(english >= 50, 'Pass', 'Fail')
pass_count = np.sum(result == 'Pass')
fail_count = np.sum(result == 'Fail')
print(f'English Pass/Fail:')
print(f'  Pass: {pass_count} students')
print(f'  Fail: {fail_count} students')

Unique ages in our data: [13 14 15 16 17 18]

English Score Percentiles:
  25th percentile: 47.0 - Bottom 25% scored below this
  50th percentile: 64.0 - Middle score (50% scored below/above this)
  75th percentile: 79.0 - Top 25% scored above this

Original max English score : 100
After capping at 95     : 95

English Pass/Fail:
  Pass: 354 students
  Fail: 146 students

In [19]:
# np.unique() -> find all unique values (no repeats)
unique_ages = np.unique(age)
print('Unique ages in our data:', unique_ages)

print()

# np.percentile() -> like "top X%"
p25 = np.percentile(science, 25)  # 25th percentile
p50 = np.percentile(science, 50)  # 50th percentile
p75 = np.percentile(science, 75)  # 75th percentile
print(f'Science Score Percentiles:')
print(f'  25th percentile: {p25} - Bottom 25% scored below this')
print(f'  50th percentile: {p50} - Middle score (50% scored below/above this)')
print(f'  75th percentile: {p75} - Top 25% scored above this')

print()

# np.clip() -> limit values between a min and max
# Let's say max score allowed is 95
science_capped = np.clip(science, 0, 95)
print(f'Original max Science score : {np.max(science)}')
print(f'After capping at 95     : {np.max(science_capped)}')

print()

# np.where() -> like IF-ELSE for arrays!
# Give grade 'Pass' if score >= 50, else 'Fail'
result = np.where(science >= 50, 'Pass', 'Fail')
pass_count = np.sum(result == 'Pass')
fail_count = np.sum(result == 'Fail')
print(f'Science Pass/Fail:')
print(f'  Pass: {pass_count} students')
print(f'  Fail: {fail_count} students')

Unique ages in our data: [13 14 15 16 17 18]

Science Score Percentiles:
  25th percentile: 47.0 - Bottom 25% scored below this
  50th percentile: 65.5 - Middle score (50% scored below/above this)
  75th percentile: 83.0 - Top 25% scored above this

Original max Science score : 100
After capping at 95     : 95

Science Pass/Fail:
  Pass: 359 students
  Fail: 141 students

In [20]:
# np.corrcoef()  gives a correlation matrix
# We want: correlation between hours studied and math score

corr_matrix = np.corrcoef(hours, math)
correlation = corr_matrix[0, 1]# top-right value in the 2x2 matrix

print(f'Correlation between Hours Studied and Math Score: {correlation:.4f}')
print()

if correlation > 0.5:
    print('Strong positive link - studying more = better math!')
elif correlation > 0.2:
    print('Weak positive link - slight trend, but not strong.')
else:
    print('Very weak/no link - hours studied alone may not predict score.')

Correlation between Hours Studied and Math Score: -0.0428

Very weak/no link - hours studied alone may not predict score.

In [21]:
# np.corrcoef()  gives a correlation matrix
# We want: correlation between hours studied and English score

corr_matrix = np.corrcoef(hours, english)
correlation = corr_matrix[0, 1]# top-right value in the 2x2 matrix

print(f'Correlation between Hours Studied and English Score: {correlation:.4f}')
print()

if correlation > 0.5:
    print('Strong positive link - studying more = better English!')
elif correlation > 0.2:
    print('Weak positive link - slight trend, but not strong.')
else:
    print('Very weak/no link - hours studied alone may not predict score.')

Correlation between Hours Studied and English Score: -0.0214

Very weak/no link - hours studied alone may not predict score.

In [22]:
# np.corrcoef()  gives a correlation matrix
# We want: correlation between hours studied and Science score

corr_matrix = np.corrcoef(hours, science)
correlation = corr_matrix[0, 1]# top-right value in the 2x2 matrix

print(f'Correlation between Hours Studied and Science Score: {correlation:.4f}')
print()

if correlation > 0.5:
    print('Strong positive link - studying more = better Science!')
elif correlation > 0.2:
    print('Weak positive link - slight trend, but not strong.')
else:
    print('Very weak/no link - hours studied alone may not predict score.')

Correlation between Hours Studied and Science Score: 0.0214

Very weak/no link - hours studied alone may not predict score.

In [23]:
df.head()

   Student_ID  Age  Math_Score  Science_Score  English_Score  Hours_Studied
0           1   16          62             49             44            7.5
1           2   17          52             40             63            2.3
2           3   15          39             67             90            2.9
3           4   17          98             35             64            8.4
4           5   17          63             52             93            3.9

In [26]:
# Add calculated columns back to the dataframe
df['Total_Score']   = total_score
df['Average_Score'] = np.round(std_avg, 2)
df['Result']        = np.where(std_avg >= 50, 'Pass', 'Fail')

# Assign letter grades
def assign_grade(avg):
    if avg >= 90: return 'A+'
    elif avg >= 80: return 'A'
    elif avg >= 70: return 'B'
    elif avg >= 60: return 'C'
    elif avg >= 50: return 'D'
    else: return 'F'

df['Grade'] = [assign_grade(a) for a in std_avg]

def assign_division(avg):
    if avg >= 75: return 'Distinction'
    elif avg >= 60: return 'First Division'
    elif avg >= 45: return 'Second Division'
    elif avg >= 33: return 'Third Division'
    else: return 'Fail'

df['Division'] = [assign_division(d) for d in std_avg]

def calculate_gpa(avg):
    if avg >= 90:
        return 4.0  # Equivalent to an A
    elif avg >= 80:
        return 3.0  # Equivalent to a B
    elif avg >= 70:
        return 2.0  # Equivalent to a C
    elif avg >= 60:
        return 1.0  # Equivalent to a D
    else:
        return 0.0  # Equivalent to an F
    
df['GPA'] = [calculate_gpa(g) for g in std_avg]

# Save to a new CSV
df.to_csv('student_results.csv', index=False)

print(' Final results saved to student_results.csv!')
print()
print(' Grade Distribution:')
print(df['Grade'].value_counts().sort_index())
print()
print(' Division Distribution:')
print(df['Division'].value_counts().sort_index())
print()
print(' GPA Distribution:')
print(df['GPA'].value_counts().sort_index())
print()
print('Last 5 rows of final data:')
df.tail()

 Final results saved to student_results.csv!

 Grade Distribution:
Grade
A      41
A+      4
B     114
C     165
D     118
F      58
Name: count, dtype: int64

 Division Distribution:
Division
Distinction         90
First Division     234
Second Division    150
Third Division      26
Name: count, dtype: int64

 GPA Distribution:
GPA
0.0    176
1.0    165
2.0    114
3.0     41
4.0      4
Name: count, dtype: int64

Last 5 rows of final data:

,Student_ID,Age,Math_Score,Science_Score,English_Score,Hours_Studied,Total_Score,Average_Score,Result,Grade,Division,GPA
495,496,16,65,98,67,7.7,230,76.67,Pass,B,Distinction,2.0
496,497,14,55,32,74,2.0,161,53.67,Pass,D,Second Division,0.0
497,498,14,72,30,64,3.8,166,55.33,Pass,D,Second Division,0.0
498,499,17,56,87,59,1.0,202,67.33,Pass,C,First Division,1.0
499,500,16,98,67,59,7.1,224,74.67,Pass,B,First Division,2.0